version: '3'

services:
  cuda-runtime-base:
    build:
      context: ./
      dockerfile: Dockerfile
      target: base
    image: cuda-runtime-base
  cuda-runtime-x86_64:
    build:
      context: ./
      dockerfile: Dockerfile
      target: base-x86_64
    image: cuda-runtime-x86_64
  app-env:
    build:
      context: ./
      dockerfile: Dockerfile
      target: ubuntu-python
    image: sigma-chan-cnn-env
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      target: ubuntu-python-surface
    container_name: sigma-chan-cnn
    image: nsakairi/sigma-chan-cnn
    ports:
      - "5560:8888"
    tty: true
    stdin_open: true
    ipc: host
    volumes:
      - "./data:/home/sigma_chan/data"
      - "./sigma_chan_network:/home/sigma_chan/sigma_chan_network"
      - "./scripts:/home/sigma_chan/scripts"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]      
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DEVICE_CAPABILITIES=all
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: sigma-chan
      MINIO_ROOT_PASSWORD: sigma-chan-dayo
    entrypoint: bash
    command: -c "/opt/bin/minio server /export --address :9999 --console-address :9001;
      mkdir -p /data/.minio.sys/buckets;
      cp -r /policies/* /data/.minio.sys/;
      /usr/bin/minio server /data"
    volumes:
      - ./data:/export
      - ./minio/policies:/policies
      - ./minio/config:/root/.minio
    ports:
      - "9000:9999"
      - "9001:9001"
